# Generated by Django 4.2.6 on 2023-10-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
