# Generated by Django 4.2.6 on 2023-10-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_alter_destination_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
    ]
